RTESQKT_LXW_LLmtcoQ03_()
RTESQKT_LXW_LLmtcoW03_()
RTESQKT_LXW_LLmtcoWWV_()
RTESQKT_LXW_LLmtcoQWV_()
RTESQKT_LXW_LLmtcoQ183_()
RTESQKT_LXW_WVLLmtco_()
RTESQKT_LXW_LLmtco_()
RTESQKT_LXW_Rcih_()
EGDDGF_LIQKTR_XLTK
GF_TKKGK_UGZG_DmkdE
GHTF_"O",_0,_"Kcuyod.Rmu"
OFHXZ_#0,_Q
ESGLT
OY_Q_=_00_ZITF_UGZG_DmkdQ
XLTK_=_Q

DmkdQ:
GHTF_"G",_0,_"Kcuyod.Rmu"
HKOFZ_#0,_"00"
ESGLT

DmkdW:
EQSS_Rcih
UGZG_DmkdW

DmkdE:
OY_TKK_=_89_ZITF_EIROK_"\Rcihusa":_UGZG_DmkdW
OY_TKK_=_8_ZITF
OY_TKS_=_00_ZITF_EQSS_LLmtcoQWV:_EIQOF_"Rcih0"
TFR_OY
TKKGK_TKK
ZkfcXavmuc:
________KTZXKF

LXW_Rcih
LEKTTF_0:_LEKTTF_5
EIROK_"\Rcihusa"
RcihLumou:
ATN_2,_"~"
LEKTTF_5
OY_XLTK_=_5_ZITF_GHTF_"O",_0,_"Xico5.Rmu"
OY_XLTK_=_0_ZITF_GHTF_"O",_0,_"Xico0.Rmu"
OY_XLTK_=_1_ZITF_GHTF_"O",_0,_"Xico1.Rmu"
OY_XLTK_=_9_ZITF_GHTF_"O",_0,_"Xico9.Rmu"
OY_XLTK_=_2_ZITF_GHTF_"O",_0,_"Xico2.Rmu"
OY_XLTK_=_8_ZITF_GHTF_"O",_0,_"Xico8.Rmu"
OY_XLTK_=_3_ZITF_GHTF_"O",_0,_"Xico3.Rmu"
OY_XLTK_=_7_ZITF_GHTF_"O",_0,_"Xico7.Rmu"
OY_XLTK_=_4_ZITF_GHTF_"O",_0,_"Xico4.Rmu"
OY_XLTK_=_6_ZITF_GHTF_"O",_0,_"Xico6.Rmu"
OY_XLTK_=_05_ZITF_GHTF_"O",_0,_"Xico05.Rmu"
OFHXZ_#0,_F$
OFHXZ_#0,_Q$
OFHXZ_#0,_Q$
OFHXZ_#0,_Q$
OFHXZ_#0,_Q$
OFHXZ_#0,_Q$
OFHXZ_#0,_Q$
OFHXZ_#0,_Q$
OFHXZ_#0,_Q$
OFHXZ_#0,_EY
OFHXZ_#0,_ED
OFHXZ_#0,_EI
OFHXZ_#0,_EW
OFHXZ_#0,_ER
OFHXZ_#0,_EZ
OFHXZ_#0,_EO
ESGLT
HQSTZZT_0,_EY:_EY_=_0
HQSTZZT_1,_ED:_ED_=_1
HQSTZZT_9,_EI:_EI_=_9
HQSTZZT_2,_ER:_ER_=_2
HQSTZZT_8,_EZ:_EZ_=_8
HQSTZZT_3,_EO:_EO_=_3
HQSTZZT_7,_EW:_EW_=_7

VORZI_25:_EGSGK_EY,_5:_ESL_:_HSQN_"DW_E91R91T91Y91U91Y91T91R91E"
HKOFZ_"ษอออออออออออออหออออออออออหอออออออออออออป"
HKOFZ_"บ_____________บ__________บ_____________บ"
HKOFZ_"ฬอออออออออออออน__________ฬอออออออออออออน"
HKOFZ_"บ_____________ศออออออออออผ_____________บ"
HKOFZ_"บ______________________________________บ"
HKOFZ_"บ______________________________________บ"
HKOFZ_"บ______________________________________บ"
HKOFZ_"บ______________________________________บ"
HKOFZ_"บ______________________________________บ"
HKOFZ_"บ______________________________________บ"
HKOFZ_"บ______________________________________บ"
HKOFZ_"บ______________________________________บ"
HKOFZ_"บ______________________________________บ"
HKOFZ_"บ______________________________________บ"
HKOFZ_"บ______________________________________บ"
HKOFZ_"บ______________________________________บ"
HKOFZ_"บ______________________________________บ"
HKOFZ_"บ______________________________________บ"
HKOFZ_"บ______________________________________บ"
HKOFZ_"บ______________________________________บ"
HKOFZ_"ฬออออออออออออออออออออออออออออออออออออออน"
HKOFZ_"บ______________________________________บ"
HKOFZ_"ศออออออออออออออออออออออออออออออออออออออผ"
ROD_M$(09)
GHTF_"O",_0,_"RcihOdxs.Rmu"
OFHXZ_#0,_sdc$
OFHXZ_#0,_urs$
OFHXZ_#0,_ulocc$
OFHXZ_#0,_Isdc$
OFHXZ_#0,_Iurs$
OFHXZ_#0,_Iulocc$
OFHXZ_#0,_Zsayico
ESGLT
M$(0)_=_"Xic_m_Wmikb_aoszomf."
M$(1)_=_sdc$
M$(9)_=_urs$
M$(2)_=_ulocc$
M$(8)_=_"Lcu_ulc_Rmuc/Zkfc."
M$(3)_=_"Kc-Esdxkzyoc_ulc_Rcihusa."
M$(7)_=_"Llcgg_us_RGL."
M$(4)_=_"Jyku_ulc_JWmikb_Rcihusa"
M$(6)_=_"Ssmv_Dkbosisxu_Vkdvsri."
M$(05)_=_"Kcuyod_us_ulc_iumouya_iboccd."
M$(00)_=_""
M$(01)_=_""
ROD_I$(09)
I$(0)_=_"Scui_wsy_yic_m_JWmikb_aoszomf.________"
I$(1)_=_Isdc$
I$(9)_=_Iurs$
I$(2)_=_Iulocc$
I$(8)_=_"Scui_wsy_icu_ulc_vmuc/ukfc."
I$(3)_=_"Scui_wsy_blmdzc_wsyo_vcihusa_icuukdzi."
I$(7)_=_"Scui_wsy_zs_us_RGL."
I$(4)_=_"Zmhci_wsy_syu_sx_JWmikb."
I$(6)_=_"Lumoui_ya_Dkbosisxu_Vkdvsri."
I$(05)_=_"Zmhci_wsy_us_ulc_iumouya_iboccd._____"
I$(00)_=_""
I$(01)_=_""
SGEQZT_1,_9,_5:_EGSGK_ER:_HKOFZ_ZODT$
SGEQZT_1,_14,_5:_EGSGK_ER:_HKOFZ_RQZT$
SGEQZT_1,_03,_5:_EGSGK_EZ:_HKOFZ_F$;_"'i"
SGEQZT_9,_04,_5:_EGSGK_EZ:_HKOFZ_"Rcihusa!"
SGEQZT_8,_1,_5:_EGSGK_EO:_HKOFZ_"Xic_byoiso_hcwi_us_blssic,"
SGEQZT_3,_1,_5:_EGSGK_EO:_HKOFZ_"Zlcd_aocii_cduco_so_iambcnmo."
Q:
Q_=_4:_W_=_0:_E_=_0
W:
SGEQZT_Q,_1,_5:_EGSGK_E:_HKOFZ_M$(W)
Q_=_Q_+_0:_W_=_W_+_0
OY_W_=_00_ZITF_Q_=_4:_W_=_0:_UGZG_E
UGZG_W:
E:
OY_E_=_ED_ZITF_UGZG_R
E_=_ED:_UGZG_W
R:
Q_=_4:_W_=_0
T:
SGEQZT_Q,_1,_5:_EGSGK_EI:_HSQN_"Y91":_HKOFZ_M$(W)
SGEQZT_11,_1,_5:_EGSGK_EW:_HKOFZ_I$(W)


____GF_ZODTK(0)_UGLXW_ZkfcXavmuc
____ZODTK_GF
____LumouZkfc_=_ZODTK
____VIOST_ZkfcHmiu_<_35
_______
________ZkfcHmiu_=_ZODTK_-_LumouZkfc
SGEQZT_1,_9,_5:_EGSGK_ER:_HKOFZ_ZODT$
W$_=_OFATN$
OY_W$_=_EIK$(5)_+_"I"_ZITF_UGZG_cz
OY_W$_=_EIK$(5)_+_"H"_ZITF_UGZG_cx
OY_W$_=_EIK$(09)_ZITF_LGXFR_0855,_1:_UGZG_bsffmdvi
OY_W$_=_"_"_ZITF_LGXFR_0855,_1:_UGZG_bsffmdvi
OY_W$_=_"~"_ZITF_EQSS_LLmtco:_TBOZ_LXW
____VTFR
____EQSS_LLmtco:_TBOZ_LXW

cx:
SGEQZT_Q,_1,_5:_EGSGK_ED:_HKOFZ_M$(W)
SGEQZT_11,_1,_5:_EGSGK_5:_HKOFZ_"______________________________________"
Q_=_Q_+_0:_W_=_W_+_0
OY_W_=_00_ZITF_Q_=_4:_W_=_0
UGZG_T
cz:
SGEQZT_Q,_1,_5:_EGSGK_ED:_HKOFZ_M$(W)
SGEQZT_11,_1,_5:_EGSGK_5:_HKOFZ_"**************************************"
Q_=_Q_-_0:_W_=_W_-_0
OY_W_=_5_ZITF_Q_=_07:_W_=_05
UGZG_T

bsffmdvi:
OY_W_=_0_ZITF_Q_=_5:_UGZG_SkiuElssic
OY_W_=_1_ZITF_Q_=_0:_UGZG_SkiuElssic
OY_W_=_9_ZITF_Q_=_1:_UGZG_SkiuElssic
OY_W_=_2_ZITF_Q_=_9:_UGZG_SkiuElssic
OY_W_=_8_ZITF_EIQOF_"Emg"
OY_W_=_3_ZITF_EIQOF_"Esdxkz"
OY_W_=_7_ZITF_VORZI_45:_LGXFR_0855,_1:_SGEQZT_0,_0,_5:_EGSGK_02:_HKOFZ_"Zwac_TB
OY_W_=_4_ZITF_SGEQZT_1,_03,_5:_EGSGK_90:_HKOFZ_"Ussv-Wwc!":_SGEQZT_9,_03,_5:_EG
OY_W_=_6_ZITF_UGZG_DmhcWmubl
OY_W_=_05_ZITF_EIQOF_"Lumouya"
EQSS_Rcih

SkiuElssic:
OY_Q_=_5_ZITF_EIQOF_"Wgkiu"
OY_Q_=_0_ZITF_EIQOF_"0gkiu"
OY_Q_=_1_ZITF_EIQOF_"1gkiu"
OY_Q_=_9_ZITF_EIQOF_"9gkiu"
EQSS_Rcih


DmhcWmubl:
GHTF_"G",_0,_"RcihLlcg.Wmu"
HKOFZ_#0,_"Tbls_Gxx"
HKOFZ_#0,_"ER_\Vkdvsri"
HKOFZ_#0,_"Vkd"
HKOFZ_#0,_"bv_\Rcihusa"
ESGLT

GHTF_"G",_0,_"Kcuyod.Wmu"
HKOFZ_#0,_"@Tbls_Gxx"
HKOFZ_#0,_"ER_\Rcihusa"
HKOFZ_#0,_"JWmikb_/oyd_Rcih0"
ESGLT
GHTF_"G",_0,_"Kcuyod.Rmu"
HKOFZ_#0,_XLTK
ESGLT
LNLZTD









TFR_LXW

LXW_LLmtco
GHTF_"O",_0,_"LLmtco.Rmu"
OFHXZ_#0,_Lmtco$
OFHXZ_#0,_Dsvc
ESGLT

OY_Lmtco$_=_"Q"_ZITF_UGZG_LmtcoQ

LmtcoW:
OY_Dsvc_=_03_ZITF_EQSS_LLmtcoW03:_TBOZ_LXW
EQSS_LLmtcoWWV:_TBOZ_LXW

LmtcoQ:
OY_Dsvc_=_183_ZITF_EQSS_LLmtcoQ183:_TBOZ_LXW
OY_Dsvc_=_03_ZITF_EQSS_LLmtcoQ03:_TBOZ_LXW
EQSS_LLmtcoQWV:_TBOZ_LXW
TFR_LXW

LXW_LLmtcoQ03
0000_LEKTTF_6:_ESL
0001_KQFRGDOMT_ZODTK
0009_E_=_OFZ(KFR_*_08)
0002_Q_=_OFZ(KFR_*_325)
0008_W_=_OFZ(KFR_*_985)
0003_R_=_OFZ(KFR_*_325)
0007_T_=_OFZ(KFR_*_985)
0004_SOFT_(Q,_W)-(R,_T),_E,_WY
0006_W$_=_OFATN$:_OY_W$_=_""_ZITF_UGZG_0016
TBOZ_LXW
0016_HSQN_"DY_H32":_UGZG_0009


TFR_LXW

LXW_LLmtcoQ183

00_LEKTTF_09:_ESL
01_KQFRGDOMT_ZODTK
09_E_=_OFZ(KFR_*_183)
02_Q_=_OFZ(KFR_*_906)
08_W_=_OFZ(KFR_*_066)
03_R_=_OFZ(KFR_*_906)
07_T_=_OFZ(KFR_*_066)
04_SOFT_(Q,_W)-(R,_T),_E,_WY
06_W$_=_OFATN$:_OY_W$_=_""_ZITF_UGZG_16
___TBOZ_LXW
16_HSQN_"DY_H32":_UGZG_09


TFR_LXW

LXW_LLmtcoQWV

000_LEKTTF_1:_ESL
001_KQFRGDOMT_ZODTK
009_E_=_OFZ(KFR_*_0)
002_Q_=_OFZ(KFR_*_396)
008_W_=_OFZ(KFR_*_066)
003_R_=_OFZ(KFR_*_396)
007_T_=_OFZ(KFR_*_066)
R_=_R_+_0
OY_R_=_455_ZITF_ESL
004_SOFT_(Q,_W)-(R,_T),_,_W
006_W$_=_OFATN$:_OY_W$_=_""_ZITF_UGZG_016
____TBOZ_LXW
016_HSQN_"DY_H32":_UGZG_009



TFR_LXW

LXW_LLmtcoW03
LEKTTF_6:_ESL
KQFRGDOMT_ZODTK
QHS:
W$_=_OFATN$
OY_W$_=_""_ZITF_UGZG_LLUUR
TBOZ_LXW

LLUUR:
Q_=_118
W_=_055

KQFG:
T_=_OFZ(KFR_*_325)
OY_T_<_055_GK_T_>_845_ZITF_UGZG_KQFG

KQFH:
Y_=_OFZ(KFR_*_985)
OY_Y_<_45_GK_Y_>_165_ZITF_UGZG_KQFH

LLQ:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_1
W_=_W_+_8
OY_W_>_135_ZITF_UGZG_LLW
UGZG_LLQ

LLW:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_8
Q_=_Q_+_8
OY_Q_>_208_ZITF_UGZG_LLE
UGZG_LLW

LLE:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_0
W_=_W_-_8
OY_W_<_055_ZITF_UGZG_LLR
UGZG_LLE

LLR:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_2
Q_=_Q_-_8
OY_Q_<_118_ZITF_UGZG_TRR
UGZG_LLR

TRR:
Q_=_118
W_=_055

LLT:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_05
W_=_W_+_8
OY_W_>_135_ZITF_UGZG_LLY
UGZG_LLT

LLY:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_09
Q_=_Q_+_8
OY_Q_>_208_ZITF_UGZG_LLU
UGZG_LLY

LLU:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_6
W_=_W_-_8
OY_W_<_055_ZITF_UGZG_LLI
UGZG_LLU

LLI:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_01
Q_=_Q_-_8
OY_Q_<_118_ZITF_UGZG_TRR1
UGZG_LLI



TRR1:
Q_=_118
W_=_055

LLO:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_5
W_=_W_+_8
OY_W_>_135_ZITF_UGZG_LLP
UGZG_LLO

LLP:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_5
Q_=_Q_+_8
OY_Q_>_208_ZITF_UGZG_LLA
UGZG_LLP

LLA:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_5
W_=_W_-_8
OY_W_<_055_ZITF_UGZG_LLS
UGZG_LLA

LLS:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_5
Q_=_Q_-_8
OY_Q_<_118_ZITF_UGZG_QHS
UGZG_LLS
TFR
TFR_LXW

LXW_LLmtcoWWV
LEKTTF_1:_ESL
KQFRGDOMT_ZODTK
WVQHS:
W$_=_OFATN$
OY_W$_=_""_ZITF
Q_=_118
W_=_055

WVKQFG:
T_=_OFZ(KFR_*_396)
OY_T_<_055_GK_T_>_845_ZITF_UGZG_WVKQFG

WVKQFH:
Y_=_OFZ(KFR_*_066)
OY_Y_<_45_GK_Y_>_055_ZITF_UGZG_WVKQFH

WVQ:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_EG
W_=_W_+_8
OY_W_>_026_ZITF_UGZG_WVW
UGZG_WVQ

WVW:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_EG
Q_=_Q_+_8
OY_Q_>_208_ZITF_UGZG_WVE
UGZG_WVW

WVE:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_EG
W_=_W_-_8
OY_W_<_85_ZITF_UGZG_WVR
UGZG_WVE

WVR:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_EG
Q_=_Q_-_8
OY_Q_<_118_ZITF_UGZG_WVTRR
UGZG_WVR

WVTRR:
Q_=_118
W_=_055

WVT:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_5
W_=_W_+_8
OY_W_>_026_ZITF_UGZG_WVY
UGZG_WVT

WVY:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_5
Q_=_Q_+_8
OY_Q_>_208_ZITF_UGZG_WVU
UGZG_WVY

WVU:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_5
W_=_W_-_8
OY_W_<_85_ZITF_UGZG_WVI
UGZG_WVU

WVI:
EG_=_OFZ(KFR_*_08)
SOFT_(T,_Y)-(Q,_W),_5
Q_=_Q_-_8
OY_Q_<_118_ZITF_UGZG_WVQHS
UGZG_WVI
TFR_OY
TBOZ_LXW


TFR_LXW

