move /y MESSAGE.BAS .\garypeek\
move /y DUMBTERM.BAS .\garypeek\
move /y SCP.BAS .\garypeek\
move /y VIEW.BAS .\garypeek\
move /y FILEMOD.BAS .\garypeek\
move /y CHKLNUM.BAS .\garypeek\
move /y EASYMENU.BAS .\garypeek\
move /y APPDFILE.BAS .\garypeek\
move /y DUATCOM.BAS .\garypeek\
move /y VOLTDIV.BAS .\garypeek\
move /y VOLTDIV.EXE .\garypeek\
move /y LM317.BAS .\garypeek\
move /y LM317.EXE .\garypeek\
move /y NE555.BAS .\garypeek\
move /y NE555.EXE .\garypeek\
move /y LEDCALC.BAS .\garypeek\
move /y LEDCALC.EXE .\garypeek\
move /y PARESIST.BAS .\garypeek\
move /y PARESIST.EXE .\garypeek\
move /y PARPORT.BAS .\garypeek\
move /y DOW.BAS .\garypeek\
move /y DTADEMO.BAS .\garypeek\
move /y DRAWPCX.BAS .\garypeek\
move /y DRAWPCXC.BAS .\garypeek\
move /y GEP.BAS .\garypeek\
move /y ANGLEMSG.BAS .\garypeek\
move /y BANNER.BAS .\garypeek\
move /y BIGCHAR.BAS .\garypeek\
move /y BARLINE.BAS .\garypeek\
move /y CAPSON.BAS .\garypeek\
move /y CIRCLE.BAS .\garypeek\
move /y EDGFXCHR.BAS .\garypeek\
move /y EPSBAS.BAS .\garypeek\
move /y EPSON.BAS .\garypeek\
move /y HEXDUMP.BAS .\garypeek\
move /y LABELOKI.BAS .\garypeek\
move /y MAKEFONT.BAS .\garypeek\
move /y LOOKFONT.BAS .\garypeek\
move /y MEMTEST.BAS .\garypeek\
move /y MOUSEPOS.BAS .\garypeek\
move /y NUMWORDS.BAS .\garypeek\
move /y OKI.BAS .\garypeek\
move /y PALETTE.BAS .\garypeek\
move /y PHONE10.BAS .\garypeek\
move /y PHONE7.BAS .\garypeek\
move /y PRINT39.BAS .\garypeek\
move /y PRNSCRN9.BAS .\garypeek\
move /y QUIZ.BAS .\garypeek\
move /y REMOVECR.BAS .\garypeek\
move /y REMREM.BAS .\garypeek\
move /y SAVEFILE.BAS .\garypeek\
move /y SPLIT.BAS .\garypeek\
move /y SWATCH.BAS .\garypeek\
move /y TXBIN.BAS .\garypeek\
move /y RXBIN.BAS .\garypeek\
move /y WHATMON.BAS .\garypeek\
move /y WSCONVRT.BAS .\garypeek\
move /y SLOWMOUS.BAS .\garypeek\
move /y PRINTEST.BAS .\garypeek\
move /y SCRNDEMO.BAS .\garypeek\