
Debut :
Cls
PRINT " ATTENTION Suivez les instructions … la lettre .... "
PRINT " -------------------------------------------------- "
print

PRINT " Vous avez choisi le mode graphique, veillez … ce que :"
PRINT " - GRAPHICS et GRAFTABL ne soit pas charg‚ "

print:print
PRINT " Appuyez sur une touche !!!!!! "
a$=input$(1):CLS:COLOR 14

PRINT " Allumez l'imprimante ! puis appuyer sur une touche ..."
a$=input$(1)
PRINT:COLOR 15

LPRINT CHR$(27);"!"

Print " Eteignez et r‚allumez l'imprimante ... Et appuyez sur une touche ..."
PRINT:COLOR 13

A$=input$(1)
Lprint "‚‚‚‚‚‚‚‚‚  TEST IMPRIMANTE ŠŠŠŠŠŠŠŠŠ "

PRINT " L'imprimante est th‚oriquement prˆte pour les applications TEXTES"
PRINT "                                           ~~~~~~~~~~~~~~~~~~~~~~~"

end


